inherit_from: .rubocop_todo.yml
Naming/FileName:
  Exclude:
    - 'lib/sesame-ruby.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'lib/sesame/api.rb'

Style/MethodMissingSuper:
  Exclude:
    - 'spec/*.rb'

Style/MissingRespondToMissing:
  Exclude:
    - 'spec/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/*.rb'
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
